dist: xenial
language: php
sudo: false
php:
- 7.1
- 7.2
- 7.3
matrix:
  fast_finish: true
script:
- vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/
- vendor/bin/phpcs --standard=PSR2 src/
- vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
- vendor/bin/phpcpd src/
install: composer install
notifications:
  email:
    recipients:
    - ottofromhell@gmail.com
    on_failure: always
env:
  global:
  - secure: qo6i5YMqLJ/ERbuWdjSwBt7FFbpWxfjRdzoMmayvigk61SJzdJJD6YFD1kSb1MXboDg7pP3j6CrziM7mNTDef/EgImIQev1NA21K3gBnhTTSGdR5Wr3U1y98ZmsXjLszq+xk6RToSojewoHua94X0ME9Xvzf8+7jWvmI0WhjanLl6oP92oRlvK3XKG2MzTLqUs8OgjtYyxa+o5NEA0QL7EQ2ML331IcmJsUj9cfuAniVIUe2+GM/CAHrTGvcfRRjNmItln0DZrvGVbxV1m1GoRnntPQXJzHvLh32LBa3VkHwjE7kapZKy5op2De8tZPqDSU1ECdpOLphBgcwOVipI8kG2N0RYdek8FCBt9bWAffS88p2cJX0YsUXHqd9Uyx4ZcvgnnZWzzN8W00X8KxqBpyuU/8CRpvYi5oQSnHWLjF8Q2CWClb1p0JaOih3I1iieIiyuVouSjawvcetEpKVEY1MZd7wPBeEOuwukv+tSrOOnSt1I92QGHHN4uRVZCsCmk8+QTHkPpDWBmYZkWCrOwdG9mM7vwmCwpGV34Ov+rqeH2TL0lKuCms30Tik4P17kYL2Dz3avHIxkJPI98lPKodTMDftTPbviJU/z28iHWSYUDhSx8a+lsyf1H+1OOnqTTCq4PC7dyH746D9QpImuhb3B4HN+y3Nr7HBsZ0XMKU=
  - secure: J2iHo/pRYXQfHsyXh/2b3vc5WFo9q6HFW1E9HlQwfwo6+GKFZHrVJmHEMcXRUcKoA4xd4ykVzl0cyo5X9nXWcZ2/mbSPSiScJiddfh07Wlp3CZXFQmfzirSM87jglWo5OSixScJJ+SDlq5cPuW2YRr6AnR64LuhyUA/3QgroE8qo8yhBovHOJE8xIYNAyN8mftJMPz6ctFwutzsU85i3rMGrxnDaF6zIQ2UtBcq/fZLaKF/fs3noLm772xlEhmrYkDgTyMGiMSAyLbcSBHV7lV3O4sJpoSOlZzD5CxhQIROG3fn8RxqiD+ADVh5nj7Md7DOoJa69NgpBOvxzWbmfA8crrbIstbGFWMspfI97C1VPc/73CgmEqWhM/K9zFC08Z+2iyjz53oIrhQmE4EhsrfebWbiq6GyGrZAiNjHC+pRmU562XAPUzdKpkR31GSegeWEYTmIgGLo2SKLheNr4g6wCam8MUcg+tPs+ZdHLtQdmkZvTCdDsH49Ik/2p711AFF6T8wSoKF6srCJlMzBYdjuahx4hz1940dFZxIX182KyODujBV5/T5+0O1oCNhE9CcriKcpvPoIOrbiG7snRrxN3EmTHXr1cz1r7D5WT8HL/Zirg2gh82gZOpvtiNmBpC35fGFVeRGGb2IvGgVXDsrbmlmST3WkHqF9ClJ9BsSk=
  - secure: Mkv/O72EBL/OO5Qy9KK2ljqE69QVaI2EblwwfjCyBSoYt9SCBjcYDIhvSP6GNpZUHkwkWEAwvwNezw+n8ymuMRyoVuMVpWjZbSkMd4IRRCHHtNsADNpO9IGhYkvSPJAnQhAIRk4JpW3QUL+x7kxRGLVz2wuwRqjj111IPcthklmPwKxjlxY6qDGMxxHqpLU8884dMy0LWZBB65onZbi8iH7Zgu18iKFGdcEGO1FFjMBmDxWi+AFr392xrot+iub7ekHjwxKlfW8ETugslq4yqZ7fQBH3lJ6KnPsCDwE7RntoWMt0fsNTvksiTGLJ/+KKGkgJc6P3RfGuby16Stcs4AJK7ccCDNHVIo+SrTBGd6LhwskeLt7F51zxFHeOnSoKLDkNOuUcQQ/zLv2mzccg6a7RxR8bWZ7/TOsOB0KrNlEeXtN5ZFf/RjUm/hoSArRNBnWc8M3Mb2Vpv4xYMwUK+Sm1k01lbdj8h4elYKbV9GtRUez4f7Ky4DFv4ioBzeB83KOd92PyZ7Kag5pe4rwrZh6BCgGJYJE1PtfaQ9RHFxHDZEv6SL52iklXTigoLB60Fuhdf+0NmjSakAGyhl8aXab9GPwlmf25O1+6Nj/fItQOVAW9X4cF/FUCvaDZHxjtDWcsAmXEyJxQWxatKNLWY5q2rk13XPVyPzrOa234Fqk=
  - secure: g/dSjzPKa5gwjGOpxS2Znnkjtd0u8Exrpquz4oiWEcI6pHVL4G0bF2mzgi8JTlA3CDtjHqdOn8HaMz03ya+AIsAY+5CRnA9tCOLIS5xXKvtI/S72Et86fApKkttyesjCuUFmtz0ilTRg2VEB6peJFosbTouSQ34xOWJdH1i9yS5ZWcBOAFtfAxI/v8uqmjP8PYSI471ge5BiWoHPc5RNA/ZPKkSluzEvjPHuP2wBASkr/AqvE8M76tTgIgN/5jd81OAup/g3el9uMkalj7rILCJdTZN5eQKtDE60xGHTl1mh+ZxlCoEX1J1/LV4CvwBmkO7FvCoUfbdkctXS9OlmQ1T40HN/a+42OSz8g0TXwFKA+mhZyFRql9gs3bhgPRzP9QDv8MBkeSBz3aSGu6HXIFzwZzc9B5fy8/TOX7ceHG/yvCiOHxG4GKvSGvZsAQXwBzkqI13S3R0Ssj10ET3SjNE6jlUlhim5n1KfGP+v3FsK97Jebnh8O35SHSwKT3m5Ty9whBAFueHPAjXFVVNCdzinlA2kLa+/tYcmVREhdXc5/3hrCnhrpvcTLgDB1UokEvSD9TgESeUOPBX61v3TFxtmWJCYN5PUmXGJxsAFakfWoTK5sgDE15wnHV0R3pAhJfuW4IZUYvRQLXfYSwXlAEkdvqbEpzAKKOZdqZ3H0Ds=
